### ISSUE TITLE
Region Label Missing

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#119]
For some alerts the region label seems to be missing:
![image](https://cloud.githubusercontent.com/assets/147369/26621041/8ff065ba-45e5-11e7-9c83-666629119504.png)

This leads to odd effects in routing, grouping etc... And the rendering of the alerts looks bugged 😄

I think this might be because some alert queries remove all labels. In Prometheus speak it ends up with something like `absent(up{job="kube-scheduler"})={}`. Somehow these rules don't apply then:

https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml#L91-L98

According to the documentation this should add a label though, so not sure what's going on.

**Comment by auhlig** [comment]
To solve for all alerts we could try:
```
alerting:
  alert_relabel_configs:
    - action: replace
       target_label: region
       replacement: {{ .Values.global.region }}
```
---
https://prometheus.io/docs/operating/configuration/#alert_relabel_configs
